PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rpubl: <http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#>

SELECT * {

    FILTER(?doc = <URI>)

    ?doc a ?doc__1_type;
        dct:identifier ?doc__1_identifier;
        dct:publisher ?doc__1_publisher .

    {

        OPTIONAL { ?doc dct:title ?doc__1_title }

        ?doc__1_type rdfs:label ?doc__1_type__1_label .

        ?doc__1_publisher foaf:name ?doc__1_publisher__1_name .

        OPTIONAL {
            ?doc rpubl:forfattningssamling ?doc__1_forfattningssamling .
            ?doc__1_forfattningssamling skos:altLabel ?doc__1_forfattningssamling__1_altLabel .
            ?doc__1_forfattningssamling skos:prefLabel ?doc__1_forfattningssamling__1_prefLabel .
        }
        OPTIONAL {
            ?doc rpubl:utredningsserie ?doc__1_utredningsserie .
            ?doc__1_utredningsserie skos:altLabel ?doc__1_utredningsserie__1_altLabel .
            ?doc__1_utredningsserie skos:prefLabel ?doc__1_utredningsserie__1_prefLabel .
        }
        OPTIONAL {
            ?doc rpubl:rattsfallspublikation ?doc__1_rattsfallspublikation .
            ?doc__1_rattsfallspublikation skos:altLabel ?doc__1_rattsfallspublikation__1_altLabel .
            ?doc__1_rattsfallspublikation skos:prefLabel ?doc__1_rattsfallspublikation__1_prefLabel .
        }
        OPTIONAL {
            ?doc rpubl:allmannaRadSerie ?doc__1_allmannaRadSerie .
            ?doc__1_allmannaRadSerie skos:altLabel ?doc__1_allmannaRadSerie__1_altLabel .
            ?doc__1_allmannaRadSerie skos:prefLabel ?doc__1_allmannaRadSerie__1_prefLabel .
        }

        OPTIONAL {
            ?doc dct:issued ?doc__1_issued
        }
        OPTIONAL {
            ?doc rpubl:beslutsdatum ?doc__1_beslutsdatum
        }
        OPTIONAL {
            ?doc rpubl:utfardandedatum ?doc__1_utfardandedatum
        }
        OPTIONAL {
            ?doc rpubl:ikrafttradandedatum ?doc__1_ikrafttradandedatum
        }
        OPTIONAL {
            ?doc rpubl:utkomFranTryck ?doc__1_utkomFranTryck
        }

    } UNION {

        OPTIONAL {
            ?doc rpubl:upphaver ?doc__upphaver .
            ?doc__upphaver a ?doc__upphaver__1_type;
                dct:identifier ?doc__upphaver__1_identifier .
            ?doc__upphaver__1_type rdfs:label ?doc__upphaver__1_type__1_label .
            OPTIONAL { ?doc__upphaver dct:title ?doc__upphaver__1_title }
        }

    }

}
