PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX sch: <http://purl.org/net/schemarama#>

CONSTRUCT {

    [] a sch:Warning;
        rdfs:isDefinedBy <http://rinfo.lagrummet.se/sys/validation/no_class.rq>;
        sch:message "Resurs [1] saknar klass."@sv;
        sch:implicated (?thing);
        dct:source ?context .

} WHERE {
    GRAPH ?context {
        ?thing ?p ?o .
        FILTER NOT EXISTS {
            ?thing a ?class
        }
    }
}
