#!/bin/sh
# Tomcat init-script
#export JAVA_HOME="/usr/lib/jvm/java-6-sun/"
export JAVA_OPTS="-Xmx1024M -Xms256M -server"
TOMCAT_USER=tomcat
RUN="sudo -u $TOMCAT_USER sh"
case $1 in
    start)
        $RUN /opt/tomcat/bin/startup.sh
    ;;
    stop)
        $RUN /opt/tomcat/bin/shutdown.sh
    ;;
    restart)
        $RUN /opt/tomcat/bin/shutdown.sh
        $RUN /opt/tomcat/bin/startup.sh
    ;;
esac
exit 0
