#! /bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch
# Description:       Starts elasticsearch using start-stop-daemon
### END INIT INFO

#ES_HOME=/usr/local/elasticsearch
ES_HOME=/opt/elasticsearch
ES_MIN_MEM=256m
ES_MAX_MEM=2g
DAEMON=$ES_HOME/bin/elasticsearch
NAME=elasticsearch
DESC=elasticsearch
PID_FILE=/var/run/$NAME.pid
LOG_DIR=/var/log/$NAME
DATA_DIR=/var/lib/$NAME
WORK_DIR=/tmp/$NAME
#CONFIG_FILE=/etc/$NAME/elasticsearch.yml
CONFIG_FILE=/$ES_HOME/config/elasticsearch.yml
DAEMON_OPTS="-p $PID_FILE -Des.config=$CONFIG_FILE -Des.path.home=$ES_HOME -Des.path.logs=$LOG_DIR -Des.path.data=$DATA_DIR -Des.path.work=$WORK_DIR"


test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $NAME"
    mkdir -p $LOG_DIR $DATA_DIR $WORK_DIR
    if start-stop-daemon -b --start --pidfile $PID_FILE --startas $DAEMON -- $DAEMON_OPTS
    then
        log_end_msg 0
    else
        if [ -f "$PID_FILE" ]; then
            rm -f "$PID_FILE"
        fi
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $NAME"
    if start-stop-daemon --stop --pidfile $PID_FILE
    then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    N=/etc/init.d/$NAME
    log_success_msg "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
