#!/bin/sh

# Tomcat init-script
JAVA_OPTS="-Xmx1024m -XX:MaxPermSize=256m -server"
TOMCAT_USER=tomcat

function tomcat() {
  sudo -u $TOMCAT_USER JAVA_OPTS="$JAVA_OPTS" sh /opt/tomcat/bin/$1.sh
}

case $1 in
    start)
        tomcat startup
    ;;
    stop)
        tomcat shutdown
    ;;
    restart)
        tomcat shutdown
        tomcat startup
    ;;
    *)
        echo "Usage: /etc/init.d/tomcat {start|stop|restart}"
        exit 1
esac

exit 0
